export {
  faArrowRight,
  faCity,
  faTrain,
  faQuestion,
  faToolbox,
  faPlaceOfWorship,
  faTheaterMasks,
  faDungeon,
  faPaperPlane,
  faStoreAlt,
  faShoppingBasket,
  faParking,
  faFileInvoiceDollar,
  faChargingStation,
  faFaucet,
  faHouseUser,
  faUmbrellaBeach,
  faCocktail,
  faWarehouse,
  faUserSecret,
  faSchool,
  faTrashAlt,
  faGraduationCap,
  faWineGlassAlt,
  faWineGlass,
  faWineBottle,
} from "@fortawesome/free-solid-svg-icons";
